# Generated by Django 4.2.1 on 2024-09-26 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spanner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spanner',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spanner',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='spanner.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='spanner',
            name='creator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creater', to='spanner.creator', verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='spanner',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='spanner.tagpost', verbose_name='Тэги'),
        ),
        migrations.AddIndex(
            model_name='spanner',
            index=models.Index(fields=['-time_create'], name='spanner_spa_time_cr_722db4_idx'),
        ),
    ]
